### PR TITLE
Handle edge case, improve model caching, enhance API, add auto GPU support, add WebUI, add CLI

### PR DESCRIPTION
**Pull request by fakerybakery**
Hi,
Thank you for releasing MeloTTS!

This PR contains several changes:

* **Fix an edge-case error:** Currently, MeloTTS splits text by sentences. If the sentences are too long, it will throw an error. I resolved this by using an alternate text splitting package that tries to split by sentences if possible, but if not it will split a sentence to avoid an error.
* **Use `cached_path` for better caching:** Currently, MeloTTS handles caching itself, however this may not work well cross-platform (also may have issues with Windows, however I have not tested this yet). `cached_path` should handle cross-platform cases better.
* **Add quiet mode:** I added a flag that allows you to suppress most logging by Melo TTS.
* **Add CLI:** This version allows you to use Melo TTS via the CLI. Example: `melo "Text to say" output.wav`. Documentation has been added to the README.
	* Supports multiple languages
	* Supports multiple speakers
	* Allows loading from file
* **Add WebUI:** I added a WebUI based on the one that powers my [unofficial demo](https://huggingface.co/spaces/mrfakename/MeloTTS). You can run it using the `melo-ui` CLI tool.
* **Add progress bar:** If you are narrating long text, a progress bar powered by `tqdm` will appear.
* **Add `auto` device:** Set the device to `auto` to automatically use a GPU if available

I also modified the README to note that macOS works since I've tested it.

Thank you!

### CODE REVIEW

**Comment by Zengyi-Qin** [comment]
This is incredibly helpful! We will start reviewing the code

**Review by wl-zhao — APPROVED** [review]
Thanks for your awesome work! All tests have been passed and this PR is ready to be merged.

**Comment by wl-zhao** [comment]
@fakerybakery Hi, please look at the latest version of [app.py](https://github.com/myshell-ai/MeloTTS/blob/main/melo/app.py). I have update the code to make the example text automatically changed with the selected language. Perhaps you can also update the [demo](https://huggingface.co/spaces/mrfakename/MeloTTS) on HF.

**Comment by fakerybakery** [comment]
Thanks! Will update tomorrow- one suggestion: do you think it might be possible to only change the text based on the language if the text in the input is the default text for that language? For example, if someone pasted text in and then changed the language after, it would be erased.

**Comment by fakerybakery** [comment]
Done!

**Pull request merged**
